Repository SIDETEAM001/side-ios, pull requests merged in 2023-11, with the labels that each got.

#2 [UPDATE] 오타수정
  README.md
Labels: update, ⚡️K⚡️

#4 [RENAME] Move the PR template file
  .github/pull_request_template
Labels: ⚡️K⚡️, rename

#27 [#26] [DELETE] : profileViewController.swift 삭제
  Projects/Feature/Profile/Sources/profileViewController.swift
Labels: 애롱, remove

#30 Feature/#29 [ADD] Add RxCocoa lib
  Projects/Shared/ThirdPartyLib/Project.swift
Labels: ⚡️K⚡️, add

#56 [#55][FEAT] 취미생활 화면 UI 그리기
  Projects/Feature/Profile/Sources/HobbyView.swift
  Projects/Feature/Profile/Sources/HobbyViewController.swift
Labels: feature, 애롱
